<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFmxvVqm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFmxvVqm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFmxvVqm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFmxvVqm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFmxvVqm\App_KernelDevDebugContainer([
    'container.build_hash' => 'FmxvVqm',
    'container.build_id' => 'd360ab58',
    'container.build_time' => 1769022081,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFmxvVqm');
