<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXSMb5Px\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXSMb5Px/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXSMb5Px.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXSMb5Px\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXSMb5Px\App_KernelDevDebugContainer([
    'container.build_hash' => 'XSMb5Px',
    'container.build_id' => 'ced0b042',
    'container.build_time' => 1777393131,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXSMb5Px');
