<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UBRkIN2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uBRkIN2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AllergenController::index' => ['privates', '.service_locator.CUAT3bv.App\\Controller\\AllergenController::index()', 'getAllergenControllerindexService', true],
            'App\\Controller\\AllergenController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\AllergenController::new()', 'getAllergenControllernewService', true],
            'App\\Controller\\AllergenController::show' => ['privates', '.service_locator..sLMoRr.App\\Controller\\AllergenController::show()', 'getAllergenControllershowService', true],
            'App\\Controller\\AllergenController::edit' => ['privates', '.service_locator.Dif0fLG.App\\Controller\\AllergenController::edit()', 'getAllergenControllereditService', true],
            'App\\Controller\\AllergenController::delete' => ['privates', '.service_locator.Dif0fLG.App\\Controller\\AllergenController::delete()', 'getAllergenControllerdeleteService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.JuymgO0.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.Cm49tF9.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.OPjDmpc.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.OPjDmpc.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.IHf39wm.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\DishController::index' => ['privates', '.service_locator.9XJG.q4.App\\Controller\\DishController::index()', 'getDishControllerindexService', true],
            'App\\Controller\\DishController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\DishController::new()', 'getDishControllernewService', true],
            'App\\Controller\\DishController::show' => ['privates', '.service_locator.SwRCox1.App\\Controller\\DishController::show()', 'getDishControllershowService', true],
            'App\\Controller\\DishController::edit' => ['privates', '.service_locator.M9wJDHN.App\\Controller\\DishController::edit()', 'getDishControllereditService', true],
            'App\\Controller\\DishController::delete' => ['privates', '.service_locator.M9wJDHN.App\\Controller\\DishController::delete()', 'getDishControllerdeleteService', true],
            'App\\Controller\\MenuController::index' => ['privates', '.service_locator.OfprUv0.App\\Controller\\MenuController::index()', 'getMenuControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReservationController::new' => ['privates', '.service_locator.IHf39wm.App\\Controller\\ReservationController::new()', 'getReservationControllernewService', true],
            'App\\Controller\\ReservationController::index' => ['privates', '.service_locator.6vVaFyG.App\\Controller\\ReservationController::index()', 'getReservationControllerindexService', true],
            'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.VwKhgOY.App\\Controller\\ReservationController::show()', 'getReservationControllershowService', true],
            'App\\Controller\\ReservationController::edit' => ['privates', '.service_locator.vedp3GS.App\\Controller\\ReservationController::edit()', 'getReservationControllereditService', true],
            'App\\Controller\\ReservationController::delete' => ['privates', '.service_locator.vedp3GS.App\\Controller\\ReservationController::delete()', 'getReservationControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SubCategoryController::index' => ['privates', '.service_locator.2ESXypc.App\\Controller\\SubCategoryController::index()', 'getSubCategoryControllerindexService', true],
            'App\\Controller\\SubCategoryController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\SubCategoryController::new()', 'getSubCategoryControllernewService', true],
            'App\\Controller\\SubCategoryController::show' => ['privates', '.service_locator.arJ0Dzc.App\\Controller\\SubCategoryController::show()', 'getSubCategoryControllershowService', true],
            'App\\Controller\\SubCategoryController::edit' => ['privates', '.service_locator.gI3UkZV.App\\Controller\\SubCategoryController::edit()', 'getSubCategoryControllereditService', true],
            'App\\Controller\\SubCategoryController::delete' => ['privates', '.service_locator.gI3UkZV.App\\Controller\\SubCategoryController::delete()', 'getSubCategoryControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AllergenController:index' => ['privates', '.service_locator.CUAT3bv.App\\Controller\\AllergenController::index()', 'getAllergenControllerindexService', true],
            'App\\Controller\\AllergenController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\AllergenController::new()', 'getAllergenControllernewService', true],
            'App\\Controller\\AllergenController:show' => ['privates', '.service_locator..sLMoRr.App\\Controller\\AllergenController::show()', 'getAllergenControllershowService', true],
            'App\\Controller\\AllergenController:edit' => ['privates', '.service_locator.Dif0fLG.App\\Controller\\AllergenController::edit()', 'getAllergenControllereditService', true],
            'App\\Controller\\AllergenController:delete' => ['privates', '.service_locator.Dif0fLG.App\\Controller\\AllergenController::delete()', 'getAllergenControllerdeleteService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.JuymgO0.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.Cm49tF9.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.OPjDmpc.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.OPjDmpc.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.IHf39wm.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\DishController:index' => ['privates', '.service_locator.9XJG.q4.App\\Controller\\DishController::index()', 'getDishControllerindexService', true],
            'App\\Controller\\DishController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\DishController::new()', 'getDishControllernewService', true],
            'App\\Controller\\DishController:show' => ['privates', '.service_locator.SwRCox1.App\\Controller\\DishController::show()', 'getDishControllershowService', true],
            'App\\Controller\\DishController:edit' => ['privates', '.service_locator.M9wJDHN.App\\Controller\\DishController::edit()', 'getDishControllereditService', true],
            'App\\Controller\\DishController:delete' => ['privates', '.service_locator.M9wJDHN.App\\Controller\\DishController::delete()', 'getDishControllerdeleteService', true],
            'App\\Controller\\MenuController:index' => ['privates', '.service_locator.OfprUv0.App\\Controller\\MenuController::index()', 'getMenuControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReservationController:new' => ['privates', '.service_locator.IHf39wm.App\\Controller\\ReservationController::new()', 'getReservationControllernewService', true],
            'App\\Controller\\ReservationController:index' => ['privates', '.service_locator.6vVaFyG.App\\Controller\\ReservationController::index()', 'getReservationControllerindexService', true],
            'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.VwKhgOY.App\\Controller\\ReservationController::show()', 'getReservationControllershowService', true],
            'App\\Controller\\ReservationController:edit' => ['privates', '.service_locator.vedp3GS.App\\Controller\\ReservationController::edit()', 'getReservationControllereditService', true],
            'App\\Controller\\ReservationController:delete' => ['privates', '.service_locator.vedp3GS.App\\Controller\\ReservationController::delete()', 'getReservationControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SubCategoryController:index' => ['privates', '.service_locator.2ESXypc.App\\Controller\\SubCategoryController::index()', 'getSubCategoryControllerindexService', true],
            'App\\Controller\\SubCategoryController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\SubCategoryController::new()', 'getSubCategoryControllernewService', true],
            'App\\Controller\\SubCategoryController:show' => ['privates', '.service_locator.arJ0Dzc.App\\Controller\\SubCategoryController::show()', 'getSubCategoryControllershowService', true],
            'App\\Controller\\SubCategoryController:edit' => ['privates', '.service_locator.gI3UkZV.App\\Controller\\SubCategoryController::edit()', 'getSubCategoryControllereditService', true],
            'App\\Controller\\SubCategoryController:delete' => ['privates', '.service_locator.gI3UkZV.App\\Controller\\SubCategoryController::delete()', 'getSubCategoryControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AllergenController::index' => '?',
            'App\\Controller\\AllergenController::new' => '?',
            'App\\Controller\\AllergenController::show' => '?',
            'App\\Controller\\AllergenController::edit' => '?',
            'App\\Controller\\AllergenController::delete' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\DishController::index' => '?',
            'App\\Controller\\DishController::new' => '?',
            'App\\Controller\\DishController::show' => '?',
            'App\\Controller\\DishController::edit' => '?',
            'App\\Controller\\DishController::delete' => '?',
            'App\\Controller\\MenuController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReservationController::new' => '?',
            'App\\Controller\\ReservationController::index' => '?',
            'App\\Controller\\ReservationController::show' => '?',
            'App\\Controller\\ReservationController::edit' => '?',
            'App\\Controller\\ReservationController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SubCategoryController::index' => '?',
            'App\\Controller\\SubCategoryController::new' => '?',
            'App\\Controller\\SubCategoryController::show' => '?',
            'App\\Controller\\SubCategoryController::edit' => '?',
            'App\\Controller\\SubCategoryController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AllergenController:index' => '?',
            'App\\Controller\\AllergenController:new' => '?',
            'App\\Controller\\AllergenController:show' => '?',
            'App\\Controller\\AllergenController:edit' => '?',
            'App\\Controller\\AllergenController:delete' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\DishController:index' => '?',
            'App\\Controller\\DishController:new' => '?',
            'App\\Controller\\DishController:show' => '?',
            'App\\Controller\\DishController:edit' => '?',
            'App\\Controller\\DishController:delete' => '?',
            'App\\Controller\\MenuController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReservationController:new' => '?',
            'App\\Controller\\ReservationController:index' => '?',
            'App\\Controller\\ReservationController:show' => '?',
            'App\\Controller\\ReservationController:edit' => '?',
            'App\\Controller\\ReservationController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SubCategoryController:index' => '?',
            'App\\Controller\\SubCategoryController:new' => '?',
            'App\\Controller\\SubCategoryController:show' => '?',
            'App\\Controller\\SubCategoryController:edit' => '?',
            'App\\Controller\\SubCategoryController:delete' => '?',
        ]);

        if (isset($container->privates['.service_locator.uBRkIN2'])) {
            return $container->privates['.service_locator.uBRkIN2'];
        }

        return $container->privates['.service_locator.uBRkIN2'] = $instance;
    }
}
