<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dif0fLGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dif0fLG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'allergen' => ['privates', '.errored..service_locator.Dif0fLG.App\\Entity\\Allergen', NULL, 'Cannot autowire service ".service_locator.Dif0fLG": it needs an instance of "App\\Entity\\Allergen" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'allergen' => 'App\\Entity\\Allergen',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.Dif0fLG'])) {
            return $container->privates['.service_locator.Dif0fLG'];
        }

        return $container->privates['.service_locator.Dif0fLG'] = $instance;
    }
}
