<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IHf39wm.App\Controller\ContactController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.IHf39wm'] ?? $container->load('get_ServiceLocator_IHf39wmService'));

        if (isset($container->privates['.service_locator.IHf39wm.App\\Controller\\ContactController::index()'])) {
            return $container->privates['.service_locator.IHf39wm.App\\Controller\\ContactController::index()'];
        }

        $instance = $a->withContext('App\\Controller\\ContactController::index()', $container);

        if (isset($container->privates['.service_locator.IHf39wm.App\\Controller\\ContactController::index()'])) {
            return $container->privates['.service_locator.IHf39wm.App\\Controller\\ContactController::index()'];
        }

        return $container->privates['.service_locator.IHf39wm.App\\Controller\\ContactController::index()'] = $instance;
    }
}
