<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDishService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.M9wJDHN.App\Entity\Dish' shared service.
     *
     * @return \App\Entity\Dish
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.M9wJDHN": it needs an instance of "App\\Entity\\Dish" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
