<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDishControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9XJG.q4.App\Controller\DishController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9XJG.q4.App\\Controller\\DishController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dishRepository' => ['privates', 'App\\Repository\\DishRepository', 'getDishRepositoryService', true],
        ], [
            'dishRepository' => 'App\\Repository\\DishRepository',
        ]))->withContext('App\\Controller\\DishController::index()', $container);
    }
}
