<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OfprUv0.App\Controller\MenuController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OfprUv0.App\\Controller\\MenuController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dishRepository' => ['privates', 'App\\Repository\\DishRepository', 'getDishRepositoryService', true],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'subCategoryRepository' => ['privates', 'App\\Repository\\SubCategoryRepository', 'getSubCategoryRepositoryService', true],
        ], [
            'dishRepository' => 'App\\Repository\\DishRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'subCategoryRepository' => 'App\\Repository\\SubCategoryRepository',
        ]))->withContext('App\\Controller\\MenuController::index()', $container);
    }
}
