<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoteUserCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\PromoteUserCommand' shared autowired service.
     *
     * @return \App\Command\PromoteUserCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/PromoteUserCommand.php';

        $container->privates['App\\Command\\PromoteUserCommand'] = $instance = new \App\Command\PromoteUserCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:promote-user');
        $instance->setDescription('Promouvoir un utilisateur en ADMIN');

        return $instance;
    }
}
