<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vedp3GS.App\Controller\ReservationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.vedp3GS'] ?? $container->load('get_ServiceLocator_Vedp3GSService'));

        if (isset($container->privates['.service_locator.vedp3GS.App\\Controller\\ReservationController::edit()'])) {
            return $container->privates['.service_locator.vedp3GS.App\\Controller\\ReservationController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\ReservationController::edit()', $container);

        if (isset($container->privates['.service_locator.vedp3GS.App\\Controller\\ReservationController::edit()'])) {
            return $container->privates['.service_locator.vedp3GS.App\\Controller\\ReservationController::edit()'];
        }

        return $container->privates['.service_locator.vedp3GS.App\\Controller\\ReservationController::edit()'] = $instance;
    }
}
