<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M9wJDHNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M9wJDHN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dish' => ['privates', '.errored..service_locator.M9wJDHN.App\\Entity\\Dish', NULL, 'Cannot autowire service ".service_locator.M9wJDHN": it needs an instance of "App\\Entity\\Dish" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dish' => 'App\\Entity\\Dish',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.M9wJDHN'])) {
            return $container->privates['.service_locator.M9wJDHN'];
        }

        return $container->privates['.service_locator.M9wJDHN'] = $instance;
    }
}
