<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GI3UkZVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gI3UkZV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'subCategory' => ['privates', '.errored..service_locator.gI3UkZV.App\\Entity\\SubCategory', NULL, 'Cannot autowire service ".service_locator.gI3UkZV": it needs an instance of "App\\Entity\\SubCategory" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'subCategory' => 'App\\Entity\\SubCategory',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.gI3UkZV'])) {
            return $container->privates['.service_locator.gI3UkZV'];
        }

        return $container->privates['.service_locator.gI3UkZV'] = $instance;
    }
}
