<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllergenControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dif0fLG.App\Controller\AllergenController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Dif0fLG'] ?? $container->load('get_ServiceLocator_Dif0fLGService'));

        if (isset($container->privates['.service_locator.Dif0fLG.App\\Controller\\AllergenController::delete()'])) {
            return $container->privates['.service_locator.Dif0fLG.App\\Controller\\AllergenController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\AllergenController::delete()', $container);

        if (isset($container->privates['.service_locator.Dif0fLG.App\\Controller\\AllergenController::delete()'])) {
            return $container->privates['.service_locator.Dif0fLG.App\\Controller\\AllergenController::delete()'];
        }

        return $container->privates['.service_locator.Dif0fLG.App\\Controller\\AllergenController::delete()'] = $instance;
    }
}
