<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllergenControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..sLMoRr.App\Controller\AllergenController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..sLMoRr.App\\Controller\\AllergenController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'allergen' => ['privates', '.errored..service_locator..sLMoRr.App\\Entity\\Allergen', NULL, 'Cannot autowire service ".service_locator..sLMoRr": it needs an instance of "App\\Entity\\Allergen" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'allergen' => 'App\\Entity\\Allergen',
        ]))->withContext('App\\Controller\\AllergenController::show()', $container);
    }
}
