<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllergenControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AllergenController' shared autowired service.
     *
     * @return \App\Controller\AllergenController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AllergenController.php';

        $container->services['App\\Controller\\AllergenController'] = $instance = new \App\Controller\AllergenController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\AllergenController', $container));

        return $instance;
    }
}
