<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDishControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M9wJDHN.App\Controller\DishController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.M9wJDHN'] ?? $container->load('get_ServiceLocator_M9wJDHNService'));

        if (isset($container->privates['.service_locator.M9wJDHN.App\\Controller\\DishController::delete()'])) {
            return $container->privates['.service_locator.M9wJDHN.App\\Controller\\DishController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\DishController::delete()', $container);

        if (isset($container->privates['.service_locator.M9wJDHN.App\\Controller\\DishController::delete()'])) {
            return $container->privates['.service_locator.M9wJDHN.App\\Controller\\DishController::delete()'];
        }

        return $container->privates['.service_locator.M9wJDHN.App\\Controller\\DishController::delete()'] = $instance;
    }
}
