<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDishControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SwRCox1.App\Controller\DishController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SwRCox1.App\\Controller\\DishController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dish' => ['privates', '.errored..service_locator.SwRCox1.App\\Entity\\Dish', NULL, 'Cannot autowire service ".service_locator.SwRCox1": it needs an instance of "App\\Entity\\Dish" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'dish' => 'App\\Entity\\Dish',
        ]))->withContext('App\\Controller\\DishController::show()', $container);
    }
}
