<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoteUserCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\PromoteUserCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\PromoteUserCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:promote-user', [], 'Promouvoir un utilisateur en ADMIN', false, #[\Closure(name: 'App\\Command\\PromoteUserCommand')] fn (): \App\Command\PromoteUserCommand => ($container->privates['App\\Command\\PromoteUserCommand'] ?? $container->load('getPromoteUserCommandService')));
    }
}
