<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VwKhgOY.App\Controller\ReservationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VwKhgOY.App\\Controller\\ReservationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.VwKhgOY.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.VwKhgOY": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'reservation' => 'App\\Entity\\Reservation',
        ]))->withContext('App\\Controller\\ReservationController::show()', $container);
    }
}
