<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubCategoryControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.arJ0Dzc.App\Controller\SubCategoryController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.arJ0Dzc.App\\Controller\\SubCategoryController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'subCategory' => ['privates', '.errored..service_locator.arJ0Dzc.App\\Entity\\SubCategory', NULL, 'Cannot autowire service ".service_locator.arJ0Dzc": it needs an instance of "App\\Entity\\SubCategory" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'subCategory' => 'App\\Entity\\SubCategory',
        ]))->withContext('App\\Controller\\SubCategoryController::show()', $container);
    }
}
