<?php

namespace ContainerFmxvVqm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubCategoryControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gI3UkZV.App\Controller\SubCategoryController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.gI3UkZV'] ?? $container->load('get_ServiceLocator_GI3UkZVService'));

        if (isset($container->privates['.service_locator.gI3UkZV.App\\Controller\\SubCategoryController::edit()'])) {
            return $container->privates['.service_locator.gI3UkZV.App\\Controller\\SubCategoryController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\SubCategoryController::edit()', $container);

        if (isset($container->privates['.service_locator.gI3UkZV.App\\Controller\\SubCategoryController::edit()'])) {
            return $container->privates['.service_locator.gI3UkZV.App\\Controller\\SubCategoryController::edit()'];
        }

        return $container->privates['.service_locator.gI3UkZV.App\\Controller\\SubCategoryController::edit()'] = $instance;
    }
}
