<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllergenControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CUAT3bv.App\Controller\AllergenController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CUAT3bv.App\\Controller\\AllergenController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'allergenRepository' => ['privates', 'App\\Repository\\AllergenRepository', 'getAllergenRepositoryService', true],
        ], [
            'allergenRepository' => 'App\\Repository\\AllergenRepository',
        ]))->withContext('App\\Controller\\AllergenController::index()', $container);
    }
}
