<?php

namespace ContainerFnJKzec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllergenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..sLMoRr.App\Entity\Allergen' shared service.
     *
     * @return \App\Entity\Allergen
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..sLMoRr": it needs an instance of "App\\Entity\\Allergen" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
